services:
  db:
    image: pgvector/pgvector:pg16
    container_name: health_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: health
    ports:
      - "5432:5432"
    volumes:
      - health_db_data:/var/lib/postgresql/data

volumes:
  health_db_data:
